# Netlify's global settings applied to the whole Bunto site

[build]
publish = "_site"
command = "bunto build"

[context.production.environment]
BUNTO_ENV = "production"

[context.deploy-preview.environment]
BUNTO_ENV = "staging"
